git:
  depth: 150

language: go
go:
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip
  include:
  - os: linux	
    arch: s390x
    go: 1.12.x
  - os: linux	
    arch: s390x
    go: tip

sudo: required

services:
  - docker

cache:
  directories:
    - "${HOME}/google-cloud-sdk/"

before_install:
  - sudo apt-get update
  # Enable ipv6 for dualstack integration test.
  - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
  - sudo ./contrib/ci.sh

install:
  - sudo apt-get install btrfs-tools
  - sudo apt-get install libseccomp2
  - sudo apt-get install libseccomp-dev
  - sudo apt-get install socat

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - docker info
  - sudo service docker status
  - make .install.gitvalidation
  - make .gitvalidation
  - make install.deps
  - mkdir -p /home/travis/gopath/src/github.com/containerd/
  - ls /home/travis/gopath/src/github.com/
  - mv /home/travis/gopath/src/github.com/cnnaik/cri /home/travis/gopath/src/github.com/containerd
  - make containerd
  - sudo PATH=$PATH GOPATH=$GOPATH make install-containerd
  - make test
  - make test-integration
  - make test-cri
after_script:
  # Abuse travis to preserve the log.
  - cat /tmp/test-integration/containerd.log
  - cat /tmp/test-cri/containerd.log
